### ISSUE TITLE
/stopcasting issue

### ISSUE THREAD

**Issue by Macumbafeh** [Lemonadez/SuperDuperMacroTBC#1]
Heyo man, 
Idk if you still fix issues with this addon.

someone reported this issue
![image](https://github.com/Lemonadez/SuperDuperMacroTBC/assets/47739411/9b1c30af-83fb-4d7a-ac5c-2ec6cdbf72b1)edit.jpg

![image](https://github.com/Lemonadez/SuperDuperMacroTBC/assets/47739411/52e2666f-fd97-4b28-9995-eafc1993e90a)edit.jpg

**Comment by Lemonadez** [comment]
I have no problem on my end. You can see /stopcasting at top of my macro

![image](https://github.com/Lemonadez/SuperDuperMacroTBC/assets/19479119/53f9e329-4542-4a19-81da-98d9885d318e)

**Comment by Macumbafeh** [comment]
Thanks for the answer !

Here is the macro if you want to copy and try with your spells. Maybe the issue is the macro.

/stopcasting
/cast [mod:ctrlalt,target=mouseover,exists,nodead,harm][mod:ctrlalt]Turn Evil; [mod:ctrl,target=mouseover,exists,nodead,help][mod:ctrl]Blessing of Sacrifice; [mod:shift,target=mouseover,exists,nodead,help][mod:shift] Blessing of Protection; [mod:alt,target=mouseover,exists,nodead,help][mod:alt] Blessing of Freedom; [target=mouseover,exists,nodead,help][] Cleanse
/use [mod:shiftalt]Medallion of the Alliance

What is strange is i ported ncBiggerMacros (https://www.wowinterface.com/downloads/info16503-ncBiggerMacros.html)
And he has no issue with it.

**Comment by Lemonadez** [comment]
the problem is the macro itself.
![image](https://github.com/Lemonadez/SuperDuperMacroTBC/assets/19479119/1c7276c9-c560-48cd-9222-ee0c1be24697)

**Comment by Lemonadez** [comment]
the issue would be hes macro. I dont have his character to test on but 
This is a proper macro. You would be able to see if you press Those modifier, You can see the Abilities on your bar changes.. 
```
/stopcasting
/cast [mod:shift] Arcane Shot
/cast [mod:ctrl] Raptor Strike
/cast Serpent Sting
```

I think the problem is that your limited to 3 modifier usage per macro in TBC. 
```
/stopcasting
/cast [mod:ctrl, target=mouseover,exists,nodead,help] Blessing of Sacrifice
/cast [mod:shift, target=mouseover,exists,nodead,help] Blessing of Protection
/cast [mod:alt, target=mouseover,exists,nodead,help] Blessing of Freedom
```

No error to show what line to fix the modifier limit per macro. I Guess that the limitation of SDM.. But anyway I used it for Scripts LOL

**Comment by Macumbafeh** [comment]
Nah i'm sure it's not limited since it works on other addons. Even on Bindpad it works.
But maybe it's a limitation from SuperDuperMacro

**Comment by Macumbafeh** [comment]
What if you had 4 modifiers then?
Also he said it works without /stopcasting that's why it's strange

**Comment by Lemonadez** [comment]
> What if you had 4 modifiers then? Also he said it works without /stopcasting that's why it's strange
```
/stopcasting
/cast [target=mouseover,mod:ctrlalt] Turn Evil;
/cast [target=mouseover,mod:ctrl] Blessing of Sacrifice;
/cast [target=mouseover,mod:shift] Blessing of Protection; 
/cast [target=mouseover,mod:alt] Blessing of Freedom;
```
That one is working. ALso even if u dont use /stopcasting you still get error
```
/cast [mod:ctrlalt,target=mouseover,exists,nodead,harm][mod:ctrlalt]Turn Evil; [mod:ctrl,target=mouseover,exists,nodead,help][mod:ctrl]Blessing of Sacrifice; [mod:shift,target=mouseover,exists,nodead,help][mod:shift] Blessing of Protection; [mod:alt,target=mouseover,exists,nodead,help][mod:alt] Blessing of Freedom; [target=mouseover,exists,nodead,help][] Cleanse
/use [mod:shiftalt]Medallion of the Alliance
```

**Comment by Macumbafeh** [comment]
Okay very strange. I have nothing to give to you to fix it ^^

**Comment by Lemonadez** [comment]
yea no other solution for it.. I mean I dont even use that much of Modifier in Macro. Dude got like 9 mods on hes 1 macro line. LOL
